apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gcp-meetup
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: gcp-meetup
    spec:
      containers:
      - image: lkysow/gcp-meetup
        name: gcp-meetup
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
