apiVersion: v1
kind: Pod
metadata:
  name: gcp-meetup
spec:
  containers:
  - image: lkysow/gcp-meetup
    name: gcp-meetup
    imagePullPolicy: Always
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
