apiVersion: v1
kind: Pod
metadata:
  name: gcp-meetup
spec:
  containers:
  - image: lkysow/gcp-meetup
    name: gcp-meetup


## with ConfigMap
#apiVersion: v1
#kind: Pod
#metadata:
#  name: gcp-meetup
#spec:
#  containers:
#  - image: lkysow/gcp-meetup
#    name: gcp-meetup
#    env:
#    - name: CONFIG
#      valueFrom:
#        configMapKeyRef:
#          # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
#          name: gcp-meetup
#          # Specify the key associated with the value
#          key: date

## With ConfigMap and Secret
#apiVersion: v1
#kind: Pod
#metadata:
#  name: gcp-meetup
#spec:
#  containers:
#  - image: lkysow/gcp-meetup
#    name: gcp-meetup
#    env:
#    - name: CONFIG
#      valueFrom:
#        configMapKeyRef:
#          name: gcp-meetup
#          key: date
#    # Secret below
#    - name: SECRET
#      valueFrom:
#        secretKeyRef:
#          name: gcp-secret
#          key: password
